project_name: ZTC
project_fullname: Zalo Traffic Control
project_description: A tool to simulate network conditions
project_github: &project_github https://github.com/duydb2/ZTC
project_license: BSD
project_irc: atcd
project_pip: true
navigation:
 - text: FAQ
   url: /docs/faq.html
 - text: docs
   url: /docs/install.html
 - text: contributing
   url: /docs/contributing.html
 - text: support
   url: /docs/support.html
 - text: github
   url: *project_github
